POST http://localhost:8080/product
Content-Type: application/json

{
  "name" : "mąka",
  "quantity" : 2,
  "description" : "notatka"
}

###

POST http://localhost:8080/shoppingList
Content-Type: application/json

{
  "name" : "budowlany"
}

###

DELETE http://localhost:8080/product/6

###

DELETE http://localhost:8080/shoppingList/1

###

GET http://localhost:8080/product/5

###

GET http://localhost:8080/shoppingList/4

###

GET http://localhost:8080/product

###

GET http://localhost:8080/shoppingList

###

PUT http://localhost:8080/shoppingList?id=4&productId=7

###